pipeline {
	agent any
	environment {
		SONAR_SCANNER = tool 'sonar7.0' // Name of your SonarQube Scanner tool
	} 	
	stages {
		stage('Clone Repository') {
		  steps {
		   git url: 'https://github.com/cygday/simple-java-from-chatgpt.git' // << replace with your repo
		  }
		}
		stage('Compile Java Code') {
		  steps {
		   sh '''
			mkdir -p build
			find . -name "*.java" > sources.txt
			javac -d build @sources.txt
		   '''
		 }
		}
		stage('Run SonarQube Analysis') {
		  steps {
			withSonarQubeEnv('sonarqube') { // Change 'MySonarSer
//ver' if your SonarQube server name is different
			 sh '''
			   ${SONAR_SCANNER}/bin/sonar-scanner \
			   -Dsonar.projectKey=simple-java-app \
			   -Dsonar.projectName=Simple Java App \
			   -Dsonar.sources=src \
			   -Dsonar.java.binaries=build
			 '''
			} 	
		  }
	       }
	}
	post {
		always {
			echo 'Cleaning workspace...'
			cleanWs()

		}
	}
}
